
volatile int var_aa = 0;
volatile int var_ab = 0;
volatile int var_ac = 0;
volatile int var_ad = 0;
volatile int var_ae = 0;
volatile int var_af = 0;
volatile int var_ag = 0;
volatile int var_ah = 0;
volatile int var_ai = 0;
volatile int var_aj = 0;
volatile int var_ba = 0;
volatile int var_bb = 0;
volatile int var_bc = 0;
volatile int var_bd = 0;
volatile int var_be = 0;
volatile int var_bf = 0;
volatile int var_bg = 0;
volatile int var_bh = 0;
volatile int var_bi = 0;
volatile int var_bj = 0;
volatile int var_ca = 0;
volatile int var_cb = 0;
volatile int var_cc = 0;
volatile int var_cd = 0;
volatile int var_ce = 0;
volatile int var_cf = 0;
volatile int var_cg = 0;
volatile int var_ch = 0;
volatile int var_ci = 0;
volatile int var_cj = 0;
volatile int var_da = 0;
volatile int var_db = 0;
volatile int var_dc = 0;
volatile int var_dd = 0;
volatile int var_de = 0;
volatile int var_df = 0;
volatile int var_dg = 0;
volatile int var_dh = 0;
volatile int var_di = 0;
volatile int var_dj = 0;
volatile int var_ea = 0;
volatile int var_eb = 0;
volatile int var_ec = 0;
volatile int var_ed = 0;
volatile int var_ee = 0;
volatile int var_ef = 0;
volatile int var_eg = 0;
volatile int var_eh = 0;
volatile int var_ei = 0;
volatile int var_ej = 0;
volatile int var_fa = 0;
volatile int var_fb = 0;
volatile int var_fc = 0;
volatile int var_fd = 0;
volatile int var_fe = 0;
volatile int var_ff = 0;
volatile int var_fg = 0;
volatile int var_fh = 0;
volatile int var_fi = 0;
volatile int var_fj = 0;
volatile int var_ga = 0;
volatile int var_gb = 0;
volatile int var_gc = 0;
volatile int var_gd = 0;
volatile int var_ge = 0;
volatile int var_gf = 0;
volatile int var_gg = 0;
volatile int var_gh = 0;
volatile int var_gi = 0;
volatile int var_gj = 0;
volatile int var_ha = 0;
volatile int var_hb = 0;
volatile int var_hc = 0;
volatile int var_hd = 0;
volatile int var_he = 0;
volatile int var_hf = 0;
volatile int var_hg = 0;
volatile int var_hh = 0;
volatile int var_hi = 0;
volatile int var_hj = 0;
volatile int var_ia = 0;
volatile int var_ib = 0;
volatile int var_ic = 0;
volatile int var_id = 0;
volatile int var_ie = 0;
volatile int var_if = 0;
volatile int var_ig = 0;
volatile int var_ih = 0;
volatile int var_ii = 0;
volatile int var_ij = 0;
volatile int var_ja = 0;
volatile int var_jb = 0;
volatile int var_jc = 0;
volatile int var_jd = 0;
volatile int var_je = 0;
volatile int var_jf = 0;
volatile int var_jg = 0;
volatile int var_jh = 0;
volatile int var_ji = 0;
volatile int var_jj = 0;

void foo()
{
    var_aa++;
    var_ab++;
    var_ac++;
    var_ad++;
    var_ae++;
    var_af++;
    var_ag++;
    var_ah++;
    var_ai++;
    var_aj++;
    var_ba++;
    var_bb++;
    var_bc++;
    var_bd++;
    var_be++;
    var_bf++;
    var_bg++;
    var_bh++;
    var_bi++;
    var_bj++;
    var_ca++;
    var_cb++;
    var_cc++;
    var_cd++;
    var_ce++;
    var_cf++;
    var_cg++;
    var_ch++;
    var_ci++;
    var_cj++;
    var_da++;
    var_db++;
    var_dc++;
    var_dd++;
    var_de++;
    var_df++;
    var_dg++;
    var_dh++;
    var_di++;
    var_dj++;
    var_ea++;
    var_eb++;
    var_ec++;
    var_ed++;
    var_ee++;
    var_ef++;
    var_eg++;
    var_eh++;
    var_ei++;
    var_ej++;
    var_fa++;
    var_fb++;
    var_fc++;
    var_fd++;
    var_fe++;
    var_ff++;
    var_fg++;
    var_fh++;
    var_fi++;
    var_fj++;
    var_ga++;
    var_gb++;
    var_gc++;
    var_gd++;
    var_ge++;
    var_gf++;
    var_gg++;
    var_gh++;
    var_gi++;
    var_gj++;
    var_ga++;
    var_gb++;
    var_gc++;
    var_gd++;
    var_ge++;
    var_gf++;
    var_gg++;
    var_gh++;
    var_gi++;
    var_gj++;
    var_ha++;
    var_hb++;
    var_hc++;
    var_hd++;
    var_he++;
    var_hf++;
    var_hg++;
    var_hh++;
    var_hi++;
    var_hj++;
    var_ia++;
    var_ib++;
    var_ic++;
    var_id++;
    var_ie++;
    var_if++;
    var_ig++;
    var_ih++;
    var_ii++;
    var_ij++;
    var_ja++;
    var_jb++;
    var_jc++;
    var_jd++;
    var_je++;
    var_jf++;
    var_jg++;
    var_jh++;
    var_ji++;
    var_jj++;
}